use phf::phf_map;

pub static STRUCT_NAME_REPLACEMENTS: phf::Map<&'static str, &'static str> = phf_map! {
    // Keep as is (from issue description)
    "SquadronPromotion" => "SquadronPromotion",

    // Generic ones
    "WingLeave" => "Empty",
    "MiningRefined" => "TypeDetails",
    "ProspectedAsteroidMaterial" => "NameAndProportion",

    "LeaveBody" => "Body",
    "MaterialDiscarded" => "MaterialCollected",
    "SquadronCreated" => "Squadron",
    "HeatDamage" => "Damage",
    "PayFines" => "Payment",
    "CarrierShipPack" => "CarrierPack",
    "SellSuit" => "Suit",
    "MissionFailed" => "Mission",
    "RenameSuitLoadout" => "SuitLoadoutLite",
    "SellWeapon" => "Weapon", 
    "ShipLocker" => "Inventory",
    "BookTaxi" => "Booking",
    "ShipyardNew" => "Ship",
    "RepairAll" => "ShipEquipmentPurchase",
    "CarrierJumpCancelled" => "Carrier",
    "RefuelPartial" => "Refuel",
    "SRVDestroyed" => "SRV",
    "QuitACrew" => "Crew",
    "PowerplayDeliver" => "PowerplayDelivery",
    "LoadoutRemoveModule" => "LoadoutEquipModule",
    "BuyTradeData" => "BuyData",
    "CrewMemberQuits" => "CrewMember",
    "DockingRequestedLandingPads" => "LandingPads",
    "CancelTaxi" => "Cancel",
    "UpgradeWeaponResource" => "Material",
    "SAASignalsFoundSignal" => "SAASignals",
    "ShipLockerMaterialsItem" => "Item",
    "TradeMicroResourcesOffered" => "MicroResources",
    "LocationPowerplayConflictProgress" => "ConflictProgress",
    "LocationFactionActiveState" => "FactionActiveState",
    "LocationFactionRecoveringState" => "FactionRecoveringState",
    "LocationSystemFaction" => "SystemFaction",
    "LocationThargoidWar" => "ThargoidWar",
    "ShipLockerMaterialsConsumable" => "Consumable",
    "LocationConflictFaction1" => "ConflictFaction1",
    "LocationConflictFaction2" => "ConflictFaction2",
    "SwitchSuitLoadoutModule" => "SuitLoadoutModule",
    "PowerplayLeave" => "PowerplayJoin",
    "MaterialTradeReceived" => "MaterialTraded",
    "ColonisationSystemClaimRelease" => "SystemClaim",
};
