// This module is a thin wrapper to attach the autogenerated event.rs to crate::journal::event
// The generated file is written by build.rs into OUT_DIR as "event.rs"
// Do not edit manually; edit codegen or schemas instead.

#![allow(clippy::all)]
#![allow(dead_code)]
include!(concat!(env!("OUT_DIR"), "/event.rs"));
