// This file is AUTO-GENERATED. Do not edit manually.
// Source: https://inara.cz/elite/components/#tab_items and https://inara.cz/elite/components/#tab_components
// Generated: 2025-08-10 23:10:54+02:00

use std::collections::HashMap;
use std::sync::OnceLock;

/// Returns a mapping from item -> locations as slices (&'static [&static str]).
pub fn items_to_locations() -> HashMap<&'static str, &'static [&'static str]> {
    let mut m: HashMap<&'static str, &'static [&'static str]> = HashMap::new();
    m.insert("Aberrant Shield Pattern Analysis", &["Ship scanning (Combat ships)", "Mission reward"]);
    m.insert("Abnormal Compact Emissions Data", &["USS (Encoded emissions)", "Ship scanning (Combat ships)", "Mission reward"]);
    m.insert("Adaptive Encryptors Capture", &["Surface POI", "USS"]);
    m.insert("Aerogel", &["RES buildings", "IND buildings", "EXT buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Anomalous Bulk Scan Data", &["Ship scanning (Transport ships)", "Mission reward"]);
    m.insert("Anomalous FSD Telemetry", &["High wake scanning", "Mission reward"]);
    m.insert("Antimony", &["Surface prospecting"]);
    m.insert("Arsenic", &["Surface prospecting", "Mining", "Mission reward"]);
    m.insert("Atypical Disrupted Wake Echoes", &["High wake scanning", "Mission reward"]);
    m.insert("Atypical Encryption Archives", &["Surface POI"]);
    m.insert("Basic Conductors", &["Ship salvage (Transport ships)"]);
    m.insert("Bio-Mechanical Conduits", &["Thargoid ship encounter"]);
    m.insert("Biotech Conductors", &["Mission reward"]);
    m.insert("Boron", &["Mining"]);
    m.insert("Cadmium", &["Surface prospecting", "Mining"]);
    m.insert("Carbon", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Carbon Fibre Plating", &["RES buildings", "Mission reward"]);
    m.insert("Caustic Crystal", &["Thargoid Maelstrom", "Thargoid Titan debris field"]);
    m.insert("Caustic Shard", &["Thargoid Maelstrom", "Thargoid Titan debris field"]);
    m.insert("Chemical Catalyst", &["RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Chemical Distillery", &["Ship salvage (Transport ships)", "USS"]);
    m.insert("Chemical Manipulators", &["Ship salvage (Transport ships)", "Surface POI", "USS (Convoy dispersal pattern)"]);
    m.insert("Chemical Processors", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Chemical Storage Units", &["Ship salvage (Transport ships)"]);
    m.insert("Chemical Superbase", &["MED room", "RES buildings", "IND buildings", "Settlements", "Mission reward"]);
    m.insert("Chromium", &["Surface prospecting", "Mining (Ice rings)"]);
    m.insert("Circuit Board", &["IND buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Circuit Switch", &["STO buildings", "RES buildings", "IND buildings", "HAB buildings", "EXT buildings", "CMD buildings", "AGRI buildings", "Settlements", "Mission reward"]);
    m.insert("Classified Scan Databanks", &["Ship scanning (Transport ships)", "Surface POI"]);
    m.insert("Classified Scan Fragment", &["Surface data point", "Mission reward", "Ship scanning (Military & authority ships)"]);
    m.insert("Compact Composites", &["USS", "Surface POI"]);
    m.insert("Compound Shielding", &["Ship salvage (Combat ships)", "USS (Encoded emissions)", "Mission reward"]);
    m.insert("Conductive Ceramics", &["Ship salvage (Transport ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Conductive Components", &["Ship salvage (Transport ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Conductive Polymers", &["Ship salvage (Transport ships)", "Surface POI", "Mission reward"]);
    m.insert("Configurable Components", &["Ship salvage (Transport ships)", "USS (Combat aftermath)", "USS (Encoded emissions)"]);
    m.insert("Core Dynamics Composites", &["Ship salvage (Combat ships)", "USS (High grade emissions)"]);
    m.insert("Corrosive Mechanisms", &["Thargoid Caustic Generator", "Thargoid Titan debris field"]);
    m.insert("Cracked Industrial Firmware", &["Surface data point", "Mission reward"]);
    m.insert("Crystal Shards", &["Ship salvage (Combat ships)", "Surface POI"]);
    m.insert("Datamined Wake Exceptions", &["High wake scanning", "Mission reward", "USS (Encoded emissions)"]);
    m.insert("Decoded Emission Data", &["Ship scanning (Combat ships)", "Mission reward"]);
    m.insert("Distorted Shield Cycle Recordings", &["Ship scanning (Transport ships)", "Mission reward"]);
    m.insert("Divergent Scan Data", &["Surface data point", "Mission reward"]);
    m.insert("Eccentric Hyperspace Trajectories", &["High wake scanning"]);
    m.insert("Electrical Fuse", &["CMD buildings", "Mission reward"]);
    m.insert("Electrical Wiring", &["IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Electrochemical Arrays", &["Ship salvage (Military & authority ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Electromagnet", &["STO buildings", "RES buildings", "CMD buildings", "Mission reward"]);
    m.insert("Encrypted Memory Chip", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Epinephrine", &["MED room", "RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Epoxy Adhesive", &["STO buildings", "RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Exceptional Scrambled Emission Data", &["Ship scanning", "USS", "Mission reward"]);
    m.insert("Exquisite Focus Crystals", &["Mission reward", "Ship salvage (Combat ships)"]);
    m.insert("Filament Composites", &["Ship salvage (Military & authority ships)", "USS"]);
    m.insert("Flawed Focus Crystals", &["Ship salvage (Combat ships)", "USS (Combat aftermath)"]);
    m.insert("Focus Crystals", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Galvanising Alloys", &["Ship salvage (Combat ships)", "USS", "Mission reward"]);
    m.insert("Germanium", &["Surface prospecting", "Mission reward"]);
    m.insert("Graphene", &["RES buildings", "HAB buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Grid Resistors", &["Ship salvage (Military & authority ships)", "USS", "Mission reward"]);
    m.insert("Guardian Module Blueprint Fragment", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Power Cell", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Power Conduit", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Sentinel Weapon Parts", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Technology Component", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Vessel Blueprint Fragment", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Weapon Blueprint Fragment", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Wreckage Components", &["Ancient/Guardian ruins"]);
    m.insert("Hardened Surface Fragments", &["Thargoid Titan"]);
    m.insert("Heat Conduction Wiring", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Heat Dispersion Plate", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Heat Exchangers", &["Ship salvage (Transport ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Heat Exposure Specimen", &["Thargoid Titan"]);
    m.insert("Heat Resistant Ceramics", &["Ship salvage (Military & authority ships)"]);
    m.insert("Heat Vanes", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("High Density Composites", &["Ship salvage (Military & authority ships)", "USS"]);
    m.insert("Hybrid Capacitors", &["Ship salvage (Military & authority ships)", "USS", "Mission reward"]);
    m.insert("Imperial Shielding", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Improvised Components", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Inconsistent Shield Soak Analysis", &["Ship scanning (Transport ships)", "Mission reward"]);
    m.insert("Ion Battery", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Iron", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Irregular Emission Data", &["Mission reward", "USS"]);
    m.insert("Lead", &["Mining"]);
    m.insert("Manganese", &["Surface prospecting", "Mission reward"]);
    m.insert("Massive Energy Surge Analytics", &["Thargoid Maelstrom"]);
    m.insert("Mechanical Components", &["Ship salvage (Transport ships)", "USS (Combat aftermath)"]);
    m.insert("Mechanical Equipment", &["Ship salvage (Transport ships)", "USS"]);
    m.insert("Mechanical Scrap", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Memory Chip", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Mercury", &["Surface prospecting"]);
    m.insert("Metal Coil", &["STO buildings", "RES buildings", "IND buildings", "CMD buildings", "AGRI buildings", "Settlements", "Mission reward"]);
    m.insert("Micro Hydraulics", &["RES buildings", "IND buildings", "Settlements", "Mission reward"]);
    m.insert("Micro Supercapacitor", &["RES buildings", "CMD buildings", "Mission reward"]);
    m.insert("Micro Thrusters", &["STO buildings", "RES buildings", "IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Micro Transformer", &["MED room", "RES buildings", "IND buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Microelectrode", &["IND buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Military Grade Alloys", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Military Supercapacitors", &["USS (High grade emissions)"]);
    m.insert("Modified Consumer Firmware", &["Mission reward", "USS", "Surface data point"]);
    m.insert("Modified Embedded Firmware", &["Surface data point", "Mission reward"]);
    m.insert("Molybdenum", &["Surface prospecting", "Mission reward"]);
    m.insert("Motor", &["STO buildings", "RES buildings", "IND buildings", "AGRI buildings", "Settlements", "Mission reward"]);
    m.insert("Nickel", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Niobium", &["Surface prospecting", "Mission reward"]);
    m.insert("Open Symmetric Keys", &["Surface data point", "USS", "Mission reward"]);
    m.insert("Optical Fibre", &["STO buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Optical Lens", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Oxygenic Bacteria", &["RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Pattern Alpha Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Beta Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Delta Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Epsilon Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Gamma Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Peculiar Shield Frequency Data", &["Ship scanning", "Mission reward"]);
    m.insert("pH Neutraliser", &["MED room", "RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Pharmaceutical Isolators", &["Mission reward", "USS (High grade emissions)"]);
    m.insert("Phase Alloys", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Phasing Membrane Residue", &["Thargoid Titan"]);
    m.insert("Phosphorus", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Polonium", &["Surface prospecting", "Mission reward"]);
    m.insert("Polymer Capacitors", &["Ship salvage (Military & authority ships)", "USS (Convoy dispersal pattern)", "Mission reward"]);
    m.insert("Precipitated Alloys", &["Ship salvage (Military & authority ships)", "Mission reward"]);
    m.insert("Proprietary Composites", &["USS (Encoded emissions)", "USS (High grade emissions)", "Mission reward"]);
    m.insert("Propulsion Elements", &["Thargoid Caustic Generator", "Thargoid Titan debris field", "Thargoid ship encounter"]);
    m.insert("Proto Heat Radiators", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Proto Light Alloys", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Proto Radiolic Alloys", &["USS (High grade emissions)"]);
    m.insert("RDX", &["STO buildings", "RES buildings", "IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Refined Focus Crystals", &["Mission reward", "USS (Weapons fire)"]);
    m.insert("Rhenium", &["Mining"]);
    m.insert("Ruthenium", &["Surface prospecting"]);
    m.insert("Salvaged Alloys", &["Ship salvage (Combat ships)", "USS (Combat aftermath)"]);
    m.insert("Scrambler", &["RES buildings", "CMD buildings", "Mission reward"]);
    m.insert("Security Firmware Patch", &["Surface data point", "Mission reward"]);
    m.insert("Selenium", &["Surface prospecting", "Mission reward"]);
    m.insert("Sensor Fragment", &["Destroyed Unknown artefact", "USS (Non-Human)", "Thargoid site"]);
    m.insert("Shield Emitters", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Shielding Sensors", &["Ship salvage (Combat ships)", "USS", "Mission reward"]);
    m.insert("Ship Flight Data", &["Thargoid ship encounter"]);
    m.insert("Ship Systems Data", &["Thargoid ship encounter"]);
    m.insert("Specialised Legacy Firmware", &["Mission reward", "Surface data point", "USS"]);
    m.insert("Strange Wake Solutions", &["High wake scanning", "Mission reward"]);
    m.insert("Sulphur", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Tactical Core Chip", &["Thargoid Revenant"]);
    m.insert("Tagged Encryption Codes", &["Surface data point", "USS", "Mission reward"]);
    m.insert("Technetium", &["Surface prospecting"]);
    m.insert("Tellurium", &["Surface prospecting"]);
    m.insert("Tempered Alloys", &["Ship salvage (Combat ships)"]);
    m.insert("Thargoid Carapace", &["Thargoid site", "Thargoid Titan debris field"]);
    m.insert("Thargoid Energy Cell", &["Thargoid site"]);
    m.insert("Thargoid Interdiction Telemetry", &["Thargoid ship encounter"]);
    m.insert("Thargoid Material Composition Data", &["Thargoid site"]);
    m.insert("Thargoid Organic Circuitry", &["Thargoid site", "Thargoid Titan debris field"]);
    m.insert("Thargoid Residue Data", &["Thargoid site"]);
    m.insert("Thargoid Ship Signature", &["Thargoid ship encounter", "Thargoid site"]);
    m.insert("Thargoid Structural Data", &["Thargoid site"]);
    m.insert("Thargoid Technological Components", &["Thargoid site"]);
    m.insert("Thargoid Wake Data", &["Thargoid ship encounter"]);
    m.insert("Thermic Alloys", &["Ship salvage (Combat ships)", "Mission reward"]);
    m.insert("Tin", &["Surface prospecting"]);
    m.insert("Titanium Plating", &["IND buildings", "Mission reward"]);
    m.insert("Transmitter", &["CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Tungsten", &["Surface prospecting"]);
    m.insert("Tungsten Carbide", &["RES buildings", "IND buildings", "EXT buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Unexpected Emission Data", &["Ship scanning (Combat ships)", "USS"]);
    m.insert("Unidentified Scan Archives", &["Ship scanning (Transport ships)"]);
    m.insert("Untypical Shield Scans", &["Ship scanning (Combat ships)"]);
    m.insert("Unusual Encrypted Files", &["Surface data point", "USS", "Mission reward"]);
    m.insert("Vanadium", &["Surface prospecting", "Mining (Ice rings)"]);
    m.insert("Viscoelastic Polymer", &["RES buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Weapon Component", &["IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Weapon Parts", &["Thargoid ship encounter"]);
    m.insert("Worn Shield Emitters", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Wreckage Components", &["Thargoid ship encounter", "Thargoid Titan debris field"]);
    m.insert("Yttrium", &["Surface prospecting"]);
    m.insert("Zinc", &["Surface prospecting"]);
    m.insert("Zirconium", &["Surface prospecting", "Mining"]);
    m
}

/// Returns the locations for a given item name.
pub fn item_locations(name: &str) -> Option<&[&'static str]> {
    ITEMS_BY_LOCATION.get_or_init(items_to_locations).get(name).map(|v| &**v)
}

static ITEMS_BY_LOCATION: OnceLock<HashMap<&'static str, &[&'static str]>> = OnceLock::new();

/// Returns a mapping from component -> locations as slices (&'static [&static str]).
pub fn components_to_locations() -> HashMap<&'static str, &'static [&'static str]> {
    let mut m: HashMap<&'static str, &'static [&'static str]> = HashMap::new();
    m.insert("Aberrant Shield Pattern Analysis", &["Ship scanning (Combat ships)", "Mission reward"]);
    m.insert("Abnormal Compact Emissions Data", &["USS (Encoded emissions)", "Ship scanning (Combat ships)", "Mission reward"]);
    m.insert("Adaptive Encryptors Capture", &["Surface POI", "USS"]);
    m.insert("Aerogel", &["RES buildings", "IND buildings", "EXT buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Anomalous Bulk Scan Data", &["Ship scanning (Transport ships)", "Mission reward"]);
    m.insert("Anomalous FSD Telemetry", &["High wake scanning", "Mission reward"]);
    m.insert("Antimony", &["Surface prospecting"]);
    m.insert("Arsenic", &["Surface prospecting", "Mining", "Mission reward"]);
    m.insert("Atypical Disrupted Wake Echoes", &["High wake scanning", "Mission reward"]);
    m.insert("Atypical Encryption Archives", &["Surface POI"]);
    m.insert("Basic Conductors", &["Ship salvage (Transport ships)"]);
    m.insert("Bio-Mechanical Conduits", &["Thargoid ship encounter"]);
    m.insert("Biotech Conductors", &["Mission reward"]);
    m.insert("Boron", &["Mining"]);
    m.insert("Cadmium", &["Surface prospecting", "Mining"]);
    m.insert("Carbon", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Carbon Fibre Plating", &["RES buildings", "Mission reward"]);
    m.insert("Caustic Crystal", &["Thargoid Maelstrom", "Thargoid Titan debris field"]);
    m.insert("Caustic Shard", &["Thargoid Maelstrom", "Thargoid Titan debris field"]);
    m.insert("Chemical Catalyst", &["RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Chemical Distillery", &["Ship salvage (Transport ships)", "USS"]);
    m.insert("Chemical Manipulators", &["Ship salvage (Transport ships)", "Surface POI", "USS (Convoy dispersal pattern)"]);
    m.insert("Chemical Processors", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Chemical Storage Units", &["Ship salvage (Transport ships)"]);
    m.insert("Chemical Superbase", &["MED room", "RES buildings", "IND buildings", "Settlements", "Mission reward"]);
    m.insert("Chromium", &["Surface prospecting", "Mining (Ice rings)"]);
    m.insert("Circuit Board", &["IND buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Circuit Switch", &["STO buildings", "RES buildings", "IND buildings", "HAB buildings", "EXT buildings", "CMD buildings", "AGRI buildings", "Settlements", "Mission reward"]);
    m.insert("Classified Scan Databanks", &["Ship scanning (Transport ships)", "Surface POI"]);
    m.insert("Classified Scan Fragment", &["Surface data point", "Mission reward", "Ship scanning (Military & authority ships)"]);
    m.insert("Compact Composites", &["USS", "Surface POI"]);
    m.insert("Compound Shielding", &["Ship salvage (Combat ships)", "USS (Encoded emissions)", "Mission reward"]);
    m.insert("Conductive Ceramics", &["Ship salvage (Transport ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Conductive Components", &["Ship salvage (Transport ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Conductive Polymers", &["Ship salvage (Transport ships)", "Surface POI", "Mission reward"]);
    m.insert("Configurable Components", &["Ship salvage (Transport ships)", "USS (Combat aftermath)", "USS (Encoded emissions)"]);
    m.insert("Core Dynamics Composites", &["Ship salvage (Combat ships)", "USS (High grade emissions)"]);
    m.insert("Corrosive Mechanisms", &["Thargoid Caustic Generator", "Thargoid Titan debris field"]);
    m.insert("Cracked Industrial Firmware", &["Surface data point", "Mission reward"]);
    m.insert("Crystal Shards", &["Ship salvage (Combat ships)", "Surface POI"]);
    m.insert("Datamined Wake Exceptions", &["High wake scanning", "Mission reward", "USS (Encoded emissions)"]);
    m.insert("Decoded Emission Data", &["Ship scanning (Combat ships)", "Mission reward"]);
    m.insert("Distorted Shield Cycle Recordings", &["Ship scanning (Transport ships)", "Mission reward"]);
    m.insert("Divergent Scan Data", &["Surface data point", "Mission reward"]);
    m.insert("Eccentric Hyperspace Trajectories", &["High wake scanning"]);
    m.insert("Electrical Fuse", &["CMD buildings", "Mission reward"]);
    m.insert("Electrical Wiring", &["IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Electrochemical Arrays", &["Ship salvage (Military & authority ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Electromagnet", &["STO buildings", "RES buildings", "CMD buildings", "Mission reward"]);
    m.insert("Encrypted Memory Chip", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Epinephrine", &["MED room", "RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Epoxy Adhesive", &["STO buildings", "RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Exceptional Scrambled Emission Data", &["Ship scanning", "USS", "Mission reward"]);
    m.insert("Exquisite Focus Crystals", &["Mission reward", "Ship salvage (Combat ships)"]);
    m.insert("Filament Composites", &["Ship salvage (Military & authority ships)", "USS"]);
    m.insert("Flawed Focus Crystals", &["Ship salvage (Combat ships)", "USS (Combat aftermath)"]);
    m.insert("Focus Crystals", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Galvanising Alloys", &["Ship salvage (Combat ships)", "USS", "Mission reward"]);
    m.insert("Germanium", &["Surface prospecting", "Mission reward"]);
    m.insert("Graphene", &["RES buildings", "HAB buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Grid Resistors", &["Ship salvage (Military & authority ships)", "USS", "Mission reward"]);
    m.insert("Guardian Module Blueprint Fragment", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Power Cell", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Power Conduit", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Sentinel Weapon Parts", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Technology Component", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Vessel Blueprint Fragment", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Weapon Blueprint Fragment", &["Ancient/Guardian ruins"]);
    m.insert("Guardian Wreckage Components", &["Ancient/Guardian ruins"]);
    m.insert("Hardened Surface Fragments", &["Thargoid Titan"]);
    m.insert("Heat Conduction Wiring", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Heat Dispersion Plate", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Heat Exchangers", &["Ship salvage (Transport ships)", "USS (Degraded emissions/Anarchy)"]);
    m.insert("Heat Exposure Specimen", &["Thargoid Titan"]);
    m.insert("Heat Resistant Ceramics", &["Ship salvage (Military & authority ships)"]);
    m.insert("Heat Vanes", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("High Density Composites", &["Ship salvage (Military & authority ships)", "USS"]);
    m.insert("Hybrid Capacitors", &["Ship salvage (Military & authority ships)", "USS", "Mission reward"]);
    m.insert("Imperial Shielding", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Improvised Components", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Inconsistent Shield Soak Analysis", &["Ship scanning (Transport ships)", "Mission reward"]);
    m.insert("Ion Battery", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Iron", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Irregular Emission Data", &["Mission reward", "USS"]);
    m.insert("Lead", &["Mining"]);
    m.insert("Manganese", &["Surface prospecting", "Mission reward"]);
    m.insert("Massive Energy Surge Analytics", &["Thargoid Maelstrom"]);
    m.insert("Mechanical Components", &["Ship salvage (Transport ships)", "USS (Combat aftermath)"]);
    m.insert("Mechanical Equipment", &["Ship salvage (Transport ships)", "USS"]);
    m.insert("Mechanical Scrap", &["Ship salvage (Transport ships)", "USS", "Mission reward"]);
    m.insert("Memory Chip", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Mercury", &["Surface prospecting"]);
    m.insert("Metal Coil", &["STO buildings", "RES buildings", "IND buildings", "CMD buildings", "AGRI buildings", "Settlements", "Mission reward"]);
    m.insert("Micro Hydraulics", &["RES buildings", "IND buildings", "Settlements", "Mission reward"]);
    m.insert("Micro Supercapacitor", &["RES buildings", "CMD buildings", "Mission reward"]);
    m.insert("Micro Thrusters", &["STO buildings", "RES buildings", "IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Micro Transformer", &["MED room", "RES buildings", "IND buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Microelectrode", &["IND buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Military Grade Alloys", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Military Supercapacitors", &["USS (High grade emissions)"]);
    m.insert("Modified Consumer Firmware", &["Mission reward", "USS", "Surface data point"]);
    m.insert("Modified Embedded Firmware", &["Surface data point", "Mission reward"]);
    m.insert("Molybdenum", &["Surface prospecting", "Mission reward"]);
    m.insert("Motor", &["STO buildings", "RES buildings", "IND buildings", "AGRI buildings", "Settlements", "Mission reward"]);
    m.insert("Nickel", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Niobium", &["Surface prospecting", "Mission reward"]);
    m.insert("Open Symmetric Keys", &["Surface data point", "USS", "Mission reward"]);
    m.insert("Optical Fibre", &["STO buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Optical Lens", &["RES buildings", "CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Oxygenic Bacteria", &["RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Pattern Alpha Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Beta Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Delta Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Epsilon Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Pattern Gamma Obelisk Data", &["Ancient/Guardian ruins"]);
    m.insert("Peculiar Shield Frequency Data", &["Ship scanning", "Mission reward"]);
    m.insert("pH Neutraliser", &["MED room", "RES buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Pharmaceutical Isolators", &["Mission reward", "USS (High grade emissions)"]);
    m.insert("Phase Alloys", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Phasing Membrane Residue", &["Thargoid Titan"]);
    m.insert("Phosphorus", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Polonium", &["Surface prospecting", "Mission reward"]);
    m.insert("Polymer Capacitors", &["Ship salvage (Military & authority ships)", "USS (Convoy dispersal pattern)", "Mission reward"]);
    m.insert("Precipitated Alloys", &["Ship salvage (Military & authority ships)", "Mission reward"]);
    m.insert("Proprietary Composites", &["USS (Encoded emissions)", "USS (High grade emissions)", "Mission reward"]);
    m.insert("Propulsion Elements", &["Thargoid Caustic Generator", "Thargoid Titan debris field", "Thargoid ship encounter"]);
    m.insert("Proto Heat Radiators", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Proto Light Alloys", &["USS (High grade emissions)", "Mission reward"]);
    m.insert("Proto Radiolic Alloys", &["USS (High grade emissions)"]);
    m.insert("RDX", &["STO buildings", "RES buildings", "IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Refined Focus Crystals", &["Mission reward", "USS (Weapons fire)"]);
    m.insert("Rhenium", &["Mining"]);
    m.insert("Ruthenium", &["Surface prospecting"]);
    m.insert("Salvaged Alloys", &["Ship salvage (Combat ships)", "USS (Combat aftermath)"]);
    m.insert("Scrambler", &["RES buildings", "CMD buildings", "Mission reward"]);
    m.insert("Security Firmware Patch", &["Surface data point", "Mission reward"]);
    m.insert("Selenium", &["Surface prospecting", "Mission reward"]);
    m.insert("Sensor Fragment", &["Destroyed Unknown artefact", "USS (Non-Human)", "Thargoid site"]);
    m.insert("Shield Emitters", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Shielding Sensors", &["Ship salvage (Combat ships)", "USS", "Mission reward"]);
    m.insert("Ship Flight Data", &["Thargoid ship encounter"]);
    m.insert("Ship Systems Data", &["Thargoid ship encounter"]);
    m.insert("Specialised Legacy Firmware", &["Mission reward", "Surface data point", "USS"]);
    m.insert("Strange Wake Solutions", &["High wake scanning", "Mission reward"]);
    m.insert("Sulphur", &["Surface prospecting", "Mining", "Mining (Ice rings)"]);
    m.insert("Tactical Core Chip", &["Thargoid Revenant"]);
    m.insert("Tagged Encryption Codes", &["Surface data point", "USS", "Mission reward"]);
    m.insert("Technetium", &["Surface prospecting"]);
    m.insert("Tellurium", &["Surface prospecting"]);
    m.insert("Tempered Alloys", &["Ship salvage (Combat ships)"]);
    m.insert("Thargoid Carapace", &["Thargoid site", "Thargoid Titan debris field"]);
    m.insert("Thargoid Energy Cell", &["Thargoid site"]);
    m.insert("Thargoid Interdiction Telemetry", &["Thargoid ship encounter"]);
    m.insert("Thargoid Material Composition Data", &["Thargoid site"]);
    m.insert("Thargoid Organic Circuitry", &["Thargoid site", "Thargoid Titan debris field"]);
    m.insert("Thargoid Residue Data", &["Thargoid site"]);
    m.insert("Thargoid Ship Signature", &["Thargoid ship encounter", "Thargoid site"]);
    m.insert("Thargoid Structural Data", &["Thargoid site"]);
    m.insert("Thargoid Technological Components", &["Thargoid site"]);
    m.insert("Thargoid Wake Data", &["Thargoid ship encounter"]);
    m.insert("Thermic Alloys", &["Ship salvage (Combat ships)", "Mission reward"]);
    m.insert("Tin", &["Surface prospecting"]);
    m.insert("Titanium Plating", &["IND buildings", "Mission reward"]);
    m.insert("Transmitter", &["CMD buildings", "Settlements", "Mission reward"]);
    m.insert("Tungsten", &["Surface prospecting"]);
    m.insert("Tungsten Carbide", &["RES buildings", "IND buildings", "EXT buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Unexpected Emission Data", &["Ship scanning (Combat ships)", "USS"]);
    m.insert("Unidentified Scan Archives", &["Ship scanning (Transport ships)"]);
    m.insert("Untypical Shield Scans", &["Ship scanning (Combat ships)"]);
    m.insert("Unusual Encrypted Files", &["Surface data point", "USS", "Mission reward"]);
    m.insert("Vanadium", &["Surface prospecting", "Mining (Ice rings)"]);
    m.insert("Viscoelastic Polymer", &["RES buildings", "CMD buildings", "AGRI buildings", "Mission reward"]);
    m.insert("Weapon Component", &["IND buildings", "CMD buildings", "Mission reward"]);
    m.insert("Weapon Parts", &["Thargoid ship encounter"]);
    m.insert("Worn Shield Emitters", &["Ship salvage (Combat ships)", "USS"]);
    m.insert("Wreckage Components", &["Thargoid ship encounter", "Thargoid Titan debris field"]);
    m.insert("Yttrium", &["Surface prospecting"]);
    m.insert("Zinc", &["Surface prospecting"]);
    m.insert("Zirconium", &["Surface prospecting", "Mining"]);
    m
}

/// Returns the locations for a given component name.
pub fn component_locations(name: &str) -> Option<&[&'static str]> {
    COMPONENTS_BY_LOCATION.get_or_init(components_to_locations).get(name).map(|v| &**v)
}

static COMPONENTS_BY_LOCATION: OnceLock<HashMap<&'static str, &[&'static str]>> = OnceLock::new();

